### PR TITLE
[Nexus] API related update, sync translations, workflow cleanup and use only Nexus for translations from now

### PR DESCRIPTION
**Pull request by AlwinEsch**
Relates to https://github.com/xbmc/xbmc/pull/21839.

### CODE REVIEW

**Review by gade01 — APPROVED** [review]

**Comment by mkreisl** [comment]
Question: Will this PR actually still be merged in this century?

**Comment by razzeee** [comment]
Bitching about it won't speed it up

**Comment by mkreisl** [comment]
> Bitching about it won't speed it up

I'm aware of that, but it might wake some people up from their hibernation.
Especially since it will soon be 3 months since the build against Kodi 20 beta is no longer possible without this PR. A poor testimony in my opinion

**Comment by ksooo** [comment]
> I'm aware of that, but it might wake some people up from their hibernation.

 I don't think so. You seem to have absolutely no clue about how software projects 100% driven by unpaid volunteers in their free time work. Have you ever thought about the possibility that people could just be busy with real life or simply cannot help here because they are sick? If it is important for you that things move forward, just make your hands dirty, learn the code base, contribute!

**Comment by mkreisl** [comment]
Oh yes, I know that very well. and what difference does it make whether a member is paid or unpaid? None! The team or the leader of the team has to make sure that a backup developer can always step in. and that is obviously not the case, I have been going through this theatre since the introduction of the binary addons. from my point of view, no one wants to take care of the maintenance. at the moment, it seems that only @AlwinEsch  is doing it. and if he is prevented from doing so, well, nothing happens. No one is interested in whether other people are dependent on it, like me for example, who feel responsible for a distribution in which Kodi plays a central role.
And believe me, I won't be taking part in this Kodi theatre for much longer. I'm too old for that now.

**Comment by ksooo** [comment]
As I said, you have no clue how things actually work if you do not even understand the difference between paid and unpaid work. 

Hint: 
paid == somebody can force you to do things
unpaid == nobody can enforce anything

**Comment by mkreisl** [comment]
But that's not the point in this case. The PR is already over 2 months old and works. So someone with the appropriate rights only has to press the button and the matter is settled. a matter of seconds.
And it is not only the developer who is responsible for this, but the WHOLE team!
And that just doesn't happen. because obviously nobody cares. 

By the way, whether it's paid or unpaid work: it's also about a certain responsibility. At least that's how I see it. When I do something, I feel responsible for it. Whether I'm paid for it or not. That makes no difference at all to me. It never has and never will.
And if you don't see it that way, then I'm sorry for all of you. because that's not a sensible basis.

So, I have now said more than I actually wanted to say. By the way, this discussion here is absolutely off topic.

**Comment by razzeee** [comment]
I can push the button, but I've never used this addon, so it might cause a SIGKILL for all I know. Do you rally want random people just merging stuff without concern?

**Comment by garbear** [comment]
Also, we just heard from the PR's author, and he's going through an incredibly difficult and devastating time in his life. @mkreisl I recommend you do one of two things (or both):

* contribute
* have some sensitivity

All the best wishes to @AlwinEsch, please put life before Kodi!

**Review by garbear — APPROVED** [review]
Code changes look 100% trivial, and I have no other concerns.

**Comment by mkreisl** [comment]
> Also, we just heard from the PR's author, and he's going through an incredibly difficult and devastating time in his life.

This is of course very bad news, hope that he will get better soon and wish him from this place all the best and good recovery.

Don't worry, I'll let this rest now that the matter is halfway resolved. and I'm building this Addon with the PR in the standard build procedure, so I know it's built correctly so far

**Review by basilgello — APPROVED** [review]
I cross-checked the PR and can approve it.

@razzeee let's have it merged, we can easily fix CI logs later on.

@mkreisl Just don't step away from contributing :)

**Comment by vpeter4** [comment]
Can this version be tagged too?

**Comment by razzeee** [comment]
Done

**Pull request merged**
